use crate::router::Router;
use crate::traits::{ModelProvider, ProviderResponse};
use crate::utils::truncate_str;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::sync::Arc;
use std::time::Instant;
use tracing::{info, warn};

/// A planned step generated by the task-start planning call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct TaskPlanStep {
    pub description: String,
    #[serde(default)]
    pub tool_hint: Option<String>,
}

/// Completion-contract signals classified by the planning LLM. Unlike the
/// keyword-based contract inference (English-only), these come from the
/// model reading the actual request in any language. All fields optional —
/// absent fields leave the keyword-inferred contract untouched.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct PlannedContractSignals {
    /// `low`, `medium`, or `high`. Permission-affecting refinements require
    /// medium or high confidence.
    #[serde(default)]
    pub confidence: Option<String>,
    #[serde(default)]
    pub expects_mutation: Option<bool>,
    #[serde(default)]
    pub requires_observation: Option<bool>,
    /// Positive outcome effects required for completion. These refine proof
    /// obligations; they do not grant permission to perform an action.
    #[serde(default)]
    pub required_effects: Option<Vec<String>>,
    #[serde(default)]
    pub task_kind: Option<String>,
    /// `allowed`, `read_only`, or `scoped`. This separates a global
    /// observation-only constraint from a request that merely forbids one
    /// operation while still requiring other changes.
    #[serde(default)]
    pub mutation_scope: Option<String>,
    /// Operation-specific constraints such as `deploy` or `send`.
    #[serde(default)]
    pub forbidden_actions: Vec<String>,
    /// Exact, verbatim spans from the current user request that support a
    /// negative mutation constraint.
    #[serde(default)]
    pub constraint_evidence: Vec<String>,
}

/// Semantic task shape used by the orchestration router. The route decision is
/// deliberately separate from the step plan: autonomous models need routing,
/// not a second model dictating how to perform the work.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct PlannedTaskShape {
    /// `inline` for work the current agent loop should finish, `durable` for
    /// work that should become a persistent background goal.
    #[serde(default)]
    pub execution_mode: Option<String>,
    /// `low`, `medium`, or `high`.
    #[serde(default)]
    pub confidence: Option<String>,
    #[serde(default)]
    pub independent_workstreams: Option<u8>,
    #[serde(default)]
    pub requires_background_continuation: Option<bool>,
}

fn confidence_is_sufficient(value: Option<&str>) -> bool {
    matches!(
        value.map(|value| value.trim().to_ascii_lowercase()),
        Some(value) if matches!(value.as_str(), "medium" | "high")
    )
}

pub(crate) fn planned_contract_is_confident(
    signals: &PlannedContractSignals,
    task_shape: Option<&PlannedTaskShape>,
) -> bool {
    confidence_is_sufficient(
        signals
            .confidence
            .as_deref()
            .or_else(|| task_shape.and_then(|shape| shape.confidence.as_deref())),
    )
}

pub(crate) fn planned_mutation_constraints_are_grounded(
    signals: &PlannedContractSignals,
    current_user_text: &str,
) -> bool {
    let scope = signals
        .mutation_scope
        .as_deref()
        .map(|value| value.trim().to_ascii_lowercase())
        .unwrap_or_default();
    if !matches!(scope.as_str(), "read_only" | "read-only" | "scoped") {
        return false;
    }
    if scope == "scoped" && signals.forbidden_actions.is_empty() {
        return false;
    }
    if matches!(scope.as_str(), "read_only" | "read-only") {
        if !signals.forbidden_actions.is_empty() || signals.expects_mutation != Some(false) {
            return false;
        }
        if signals.task_kind.as_deref().is_some_and(|kind| {
            matches!(
                kind.trim().to_ascii_lowercase().as_str(),
                "change" | "deliver" | "schedule" | "monitor"
            )
        }) {
            return false;
        }
    }

    let current_lower = current_user_text.to_lowercase();
    !signals.constraint_evidence.is_empty()
        && signals.constraint_evidence.iter().all(|evidence| {
            let evidence = evidence.trim();
            !evidence.is_empty()
                && evidence.chars().count() <= 500
                && current_lower.contains(&evidence.to_lowercase())
        })
}

/// How much task scaffolding the active model needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TaskAssessmentMode {
    /// Produce a concrete step plan for models that benefit from supervision.
    GuidedPlan,
    /// Classify only the contract and orchestration shape. The primary model
    /// remains responsible for its own approach.
    AutonomousRouting,
}

impl TaskAssessmentMode {
    pub(crate) fn includes_step_plan(self) -> bool {
        matches!(self, Self::GuidedPlan)
    }

    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::GuidedPlan => "guided_plan",
            Self::AutonomousRouting => "autonomous_routing",
        }
    }
}

/// Raw response from the task assessment call.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TaskPlanResponse {
    #[serde(default = "task_contract_schema_version")]
    schema_version: u16,
    goal: String,
    #[serde(default)]
    steps: Vec<TaskPlanStep>,
    #[serde(default)]
    success_criteria: Vec<String>,
    #[serde(default)]
    contract: Option<PlannedContractSignals>,
    #[serde(default)]
    task_shape: Option<PlannedTaskShape>,
}

const TASK_CONTRACT_SCHEMA_VERSION: u16 = 1;

const fn task_contract_schema_version() -> u16 {
    TASK_CONTRACT_SCHEMA_VERSION
}

/// Result of the task-start assessment call.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub(crate) struct TaskPlan {
    pub goal: String,
    pub steps: Vec<TaskPlanStep>,
    pub success_criteria: Vec<String>,
    pub contract: Option<PlannedContractSignals>,
    pub task_shape: Option<PlannedTaskShape>,
    pub mode: TaskAssessmentMode,
}

const MAX_PLAN_STEPS: usize = 7;

#[derive(Clone, Copy)]
pub(crate) struct PlannerTelemetryCtx<'a> {
    pub emitter: &'a crate::events::EventEmitter,
    pub state: &'a dyn crate::traits::TokenUsageStore,
    pub session_id: &'a str,
    pub task_id: &'a str,
}

async fn record_auxiliary_model_call(
    telemetry: Option<PlannerTelemetryCtx<'_>>,
    call_purpose: &str,
    model: &str,
    response: &ProviderResponse,
    latency_ms: u64,
) {
    let Some(telemetry) = telemetry else {
        return;
    };
    let (
        input_tokens,
        output_tokens,
        cached_input_tokens,
        cache_creation_input_tokens,
        fresh_input_tokens,
    ) = response
        .usage
        .as_ref()
        .map(|usage| {
            (
                usage.input_tokens,
                usage.output_tokens,
                usage.cached_input_tokens,
                usage.cache_creation_input_tokens,
                usage.fresh_input_tokens(),
            )
        })
        .unwrap_or((0, 0, None, None, None));
    crate::events::record_model_call_telemetry(
        telemetry.emitter,
        telemetry.state,
        crate::events::ModelCallTelemetryInput {
            session_id: telemetry.session_id.to_string(),
            task_id: telemetry.task_id.to_string(),
            call_purpose: Some(call_purpose.to_string()),
            iteration: Some(0),
            llm_call: crate::events::LlmCallData {
                call_id: None,
                call_purpose: Some(call_purpose.to_string()),
                task_id: telemetry.task_id.to_string(),
                iteration: Some(0),
                model: model.to_string(),
                final_model: Some(model.to_string()),
                fell_back: false,
                attempts: 1,
                latency_ms,
                prompt_ms: None,
                decode_ms: None,
                input_tokens,
                output_tokens,
                cached_input_tokens,
                cache_creation_input_tokens,
                fresh_input_tokens,
                est_input_tokens: None,
                tool_calls_count: response.tool_calls.len() as u32,
                offered_tools: Vec::new(),
                chosen_tools: Vec::new(),
                build_ms: None,
                prefix_hash_system: None,
                prefix_hash_pre_boundary: None,
                tool_defs_hash: None,
                session_summary_hash: None,
                tail_hash: None,
                prefix_hash_archived: None,
                boundary_pos: None,
                message_count: None,
                force_text: false,
                token_usage_present: response.usage.is_some(),
                failed: false,
                error: None,
            },
            token_usage: response.usage.clone(),
        },
    )
    .await;
}

/// Assess the user's request for a Guided model before its main loop.
/// Autonomous models do not invoke this auxiliary classifier or step planner.
///
/// Returns None if the assessment call fails, times out, or returns
/// unparseable JSON. Failure is silent and callers continue without a plan.
#[allow(dead_code)]
pub(crate) async fn generate_task_plan(
    provider: Arc<dyn ModelProvider>,
    model: &str,
    user_text: &str,
    conversation_context: Option<&str>,
    mode: TaskAssessmentMode,
    telemetry: Option<PlannerTelemetryCtx<'_>>,
) -> Option<TaskPlan> {
    let system = "You are a task assessment router. Read the request semantically in its \
                  original language and return ONLY valid JSON, with no markdown fences.";

    // Include conversation context from the sliding window so the planner
    // has the same narrative as the main LLM. Without this, short follow-ups
    // like "and for ibuprofen?" lose the original intent from earlier turns.
    let context_block = conversation_context
        .filter(|ctx| !ctx.is_empty())
        .map(|ctx| format!("Recent conversation context:\n{}\n\n", ctx))
        .unwrap_or_default();

    let plan_instructions = if mode.includes_step_plan() {
        "- Return 2-7 concrete steps and concrete success criteria.\n\
         - tool_hint is advisory.\n\
         - Keep each distinct action in its own step; do not collapse build, run, fix, \
           deploy, and verify into one step.\n\
         - When creating a file that processes other files, begin by inspecting the \
           target format."
    } else {
        "- Return steps=[] and success_criteria=[]. Do not plan the model's approach; \
           this call only classifies routing and obligations."
    };

    let user_prompt = format!(
        "{context_block}Assess this user request.\n\n\
         User request: \"{user_text}\"\n\n\
         Return exactly this JSON shape:\n\
         {{\n\
           \"schema_version\": 1,\n\
           \"goal\": \"one-line semantic summary\",\n\
           \"steps\": [],\n\
           \"success_criteria\": [],\n\
           \"contract\": {{\n\
             \"confidence\": \"low|medium|high\",\n\
             \"task_kind\": \"conversational|answer|check|find|change|deliver|schedule|monitor|diagnose\",\n\
             \"expects_mutation\": true,\n\
             \"requires_observation\": true,\n\
             \"required_effects\": [\"local_source_write\", \"remote_deploy\"],\n\
             \"mutation_scope\": \"allowed|read_only|scoped\",\n\
             \"forbidden_actions\": [\"deploy\"],\n\
             \"constraint_evidence\": [\"exact verbatim span from the current user request\"]\n\
           }},\n\
           \"task_shape\": {{\n\
             \"execution_mode\": \"inline|durable\",\n\
             \"confidence\": \"low|medium|high\",\n\
             \"independent_workstreams\": 1,\n\
             \"requires_background_continuation\": false\n\
           }}\n\
         }}\n\n\
         Classification rules:\n\
         - Judge meaning, scope, and outcomes in whatever language the user wrote. \
           Do not classify by isolated keywords.\n\
         - execution_mode=inline for answers, lookups, small artifacts, and one \
           cohesive change that the current loop should finish, even when it should \
           run a test afterward.\n\
         - execution_mode=durable only when continuation outside the current run is \
           operationally necessary: explicit background/asynchronous work, waiting on an \
           external condition, monitoring, cross-project work, or multiple genuinely \
           independent workstreams.\n\
         - A long or multi-stage request is not automatically durable. One cohesive target \
           remains inline even when the same agent must build, deploy, verify, and return \
           an external URL. Persistence and task decomposition are separate decisions.\n\
         - expects_mutation=true only when completion changes files or external state. \
           Text generated in the reply is not a mutation.\n\
         - requires_observation=true when live files, commands, web pages, APIs, or \
           current state must be read.\n\
         - required_effects names the successful effects completion must prove. Valid \
           values are local_source_write, repository_write, remote_mutation, \
           remote_deploy, external_delivery, process_state, configuration, and \
           destructive. Use [] when expects_mutation=false. A build cache or installed \
           dependency is not a local_source_write.\n\
         - mutation_scope=read_only only when the whole task forbids changes. Use \
           mutation_scope=scoped when the task still requires changes but forbids only \
           named operations. Example: build locally but do not deploy => scoped, \
           expects_mutation=true, forbidden_actions=[\"deploy\"].\n\
         - Valid forbidden_actions values are create, delete, deploy, publish, post, and send. \
           Include only operations actually forbidden by the current request. A content, retry, \
           or precondition guard is not an operation-wide ban: for example, \"do not post \
           secrets\", \"do not post filler\", and \"do not post if identity verification fails\" \
           must not produce forbidden_actions=[\"post\"].\n\
         - mutation_scope=allowed when there is no negative mutation constraint; then \
           forbidden_actions and constraint_evidence must be empty.\n\
         - For read_only or scoped, constraint_evidence must contain the exact verbatim \
           words in the CURRENT user request that impose the restriction. Never derive \
           a restriction from recent conversation context, this prompt's examples, or an \
           inferred phrase that the user did not write.\n\
         {plan_instructions}",
        user_text = truncate_str(user_text, 4000),
    );

    let messages = vec![
        json!({ "role": "system", "content": system }),
        json!({ "role": "user", "content": user_prompt }),
    ];

    let call_start = Instant::now();
    let result = match tokio::time::timeout(
        std::time::Duration::from_secs(15),
        provider.chat(model, &messages, &[]),
    )
    .await
    {
        Ok(Ok(response)) => response,
        Ok(Err(e)) => {
            warn!(error = %e, "Task assessment call failed");
            return None;
        }
        Err(_) => {
            warn!("Task assessment call timed out (15s)");
            return None;
        }
    };
    record_auxiliary_model_call(
        telemetry,
        "task_assessment",
        model,
        &result,
        call_start.elapsed().as_millis() as u64,
    )
    .await;

    let content = result.content.as_deref().unwrap_or("");

    let json_str = match crate::utils::extract_json_object(content) {
        Some(s) => s,
        None => {
            warn!("Task assessment response: no valid JSON found");
            return None;
        }
    };

    let parsed: TaskPlanResponse = match serde_json::from_str(&json_str) {
        Ok(p) => p,
        Err(e) => {
            warn!(error = %e, "Task assessment response unparseable");
            return None;
        }
    };

    if parsed.schema_version != TASK_CONTRACT_SCHEMA_VERSION {
        warn!(
            received = parsed.schema_version,
            supported = TASK_CONTRACT_SCHEMA_VERSION,
            "Task assessment response used an unsupported schema version"
        );
        return None;
    }

    if parsed.contract.is_none() && parsed.task_shape.is_none() && parsed.steps.is_empty() {
        return None;
    }

    let mut steps = parsed.steps;
    let mut success_criteria = parsed.success_criteria;
    if !mode.includes_step_plan() {
        steps.clear();
        success_criteria.clear();
    }

    steps.truncate(MAX_PLAN_STEPS);

    info!(
        goal = %parsed.goal,
        step_count = steps.len(),
        assessment_mode = mode.as_str(),
        "Task assessment generated"
    );

    Some(TaskPlan {
        goal: parsed.goal,
        steps,
        success_criteria,
        contract: parsed.contract,
        task_shape: parsed.task_shape,
        mode,
    })
}

/// Determine whether a turn bypasses the optional task-start assessment.
/// Semantic task interpretation belongs to the model. Only protocol-level
/// acknowledgments and exact emergency control commands bypass assessment.
#[cfg(test)]
fn should_skip_planning(
    _task_kind: &crate::agent::CompletionTaskKind,
    user_text: &str,
    is_acknowledgment: bool,
) -> bool {
    planning_skip_reason(user_text, is_acknowledgment).is_some()
}

pub(crate) fn planning_skip_reason(
    user_text: &str,
    is_acknowledgment: bool,
) -> Option<&'static str> {
    if is_acknowledgment {
        return Some("acknowledgment");
    }

    // Exact control commands are handled by the typed bootstrap protocol.
    let lower = user_text.trim().to_lowercase();
    let control_commands = [
        "cancel",
        "stop",
        "nevermind",
        "never mind",
        "abort",
        "forget it",
        "forget that",
        "nvm",
    ];
    if control_commands.iter().any(|cmd| lower == *cmd) {
        return Some("control_command");
    }

    None
}

/// Re-planner: evaluates whether the current plan step is complete.
///
/// Called after each tool execution round when the current step has had
/// enough tool calls since the last evaluation. Uses a focused LLM
/// prompt to judge step completion.
///
/// Returns Some(evidence) if the step is complete, None if not or on failure.
pub(crate) async fn evaluate_step_completion(
    provider: Arc<dyn ModelProvider>,
    router: &Router,
    step_description: &str,
    tool_results_summary: &str,
    telemetry: Option<PlannerTelemetryCtx<'_>>,
) -> Option<String> {
    let model = router.select(crate::router::Tier::Primary).to_string();

    let prompt = format!(
        "You are evaluating whether a task step is complete.\n\n\
         Current step: \"{}\"\n\n\
         Tool results from this step:\n{}\n\n\
         Has the agent gathered enough information or completed enough work \
         to move to the next step? Be practical \u{2014} if the key information \
         has been found, the step is complete even if more could theoretically \
         be explored.\n\n\
         Return JSON only:\n\
         {{\"complete\": true/false, \"evidence\": \"brief summary of what was accomplished\"}}",
        step_description,
        truncate_str(tool_results_summary, 1500)
    );

    let messages = vec![
        json!({
            "role": "system",
            "content": "You are a task progress evaluator. Return ONLY valid JSON."
        }),
        json!({ "role": "user", "content": prompt }),
    ];

    let call_start = Instant::now();
    let result = match tokio::time::timeout(
        std::time::Duration::from_secs(10),
        provider.chat(&model, &messages, &[]),
    )
    .await
    {
        Ok(Ok(response)) => response,
        Ok(Err(e)) => {
            warn!(error = %e, "Re-planner call failed");
            return None;
        }
        Err(_) => {
            warn!("Re-planner call timed out (10s)");
            return None;
        }
    };
    record_auxiliary_model_call(
        telemetry,
        "replanner",
        &model,
        &result,
        call_start.elapsed().as_millis() as u64,
    )
    .await;

    let content = result.content.as_deref().unwrap_or("");
    let json_str = crate::utils::extract_json_object(content)?;

    #[derive(Deserialize)]
    struct ReplanResult {
        complete: bool,
        #[serde(default)]
        evidence: String,
    }

    match serde_json::from_str::<ReplanResult>(&json_str) {
        Ok(r) if r.complete => {
            info!(evidence = %r.evidence, "Re-planner: step complete");
            Some(r.evidence)
        }
        Ok(_) => {
            info!("Re-planner: step not yet complete");
            None
        }
        Err(e) => {
            warn!(error = %e, "Re-planner response parse failed");
            None
        }
    }
}

/// Build a summary of recent tool calls for the re-planner prompt.
pub(crate) fn summarize_tool_calls_for_replan(tool_calls: &[String], max_entries: usize) -> String {
    tool_calls
        .iter()
        .rev()
        .take(max_entries)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .map(|call| {
            let display = crate::agent::post_task::display_tool_call(call);
            format!("- {}", display)
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conversational_turn_gets_semantic_assessment() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Conversational,
            "hello there how are you doing today",
            false
        ));
    }

    #[test]
    fn short_turn_gets_semantic_assessment() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Find,
            "hi",
            false
        ));
    }

    #[test]
    fn direct_recall_question_gets_semantic_assessment() {
        use crate::agent::CompletionTaskKind;
        assert_eq!(planning_skip_reason("What's my dad's name?", false), None);
        assert!(!should_skip_planning(
            &CompletionTaskKind::Answer,
            "What's the source of that?",
            false
        ));
    }

    #[test]
    fn artifact_request_gets_semantic_assessment() {
        let request = "Can you create a pptx about Ecuador. Make it beautiful as I will present in my daughter's school.";

        assert_eq!(planning_skip_reason(request, false), None);
    }

    #[test]
    fn test_should_skip_control_commands() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "cancel",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "stop",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "nevermind",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "nvm",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "abort",
            false
        ));
    }

    #[test]
    fn timed_request_gets_semantic_assessment() {
        use crate::agent::CompletionTaskKind;
        assert_eq!(
            planning_skip_reason("Check deployment tomorrow at 9am", false),
            None
        );
        assert!(!should_skip_planning(
            &CompletionTaskKind::Change,
            "Check deployment tomorrow at 9am",
            false
        ));
    }

    #[test]
    fn cadence_inside_draft_only_request_is_not_a_schedule_route() {
        let request = "Prepare a mandate draft that reviews every 15 minutes. Do not schedule, create, or activate anything.";
        assert_eq!(planning_skip_reason(request, false), None);
    }

    #[test]
    fn test_should_skip_acknowledgment() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Change,
            "ok thanks that looks good",
            true
        ));
    }

    #[test]
    fn test_should_not_skip_investigative_question() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Find,
            "Can you figure out how the Twitter scheduled task got removed?",
            false
        ));
    }

    #[test]
    fn test_should_not_skip_change_task() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Change,
            "Create a website about zeigarnik effect and deploy to cloudflare",
            false
        ));
    }

    #[test]
    fn long_non_english_request_gets_semantic_assessment() {
        let request = "Construye una aplicación completa, configura la entrega externa, \
            comprueba el resultado final y comparte el enlace cuando todo esté listo.";

        assert_eq!(planning_skip_reason(request, false), None);
    }

    #[test]
    fn test_parse_plan_response() {
        let json = r#"{
            "goal": "Find how Twitter task was removed",
            "steps": [
                {"description": "Search memory for twitter schedule", "tool_hint": "manage_memories"},
                {"description": "Check goal trace", "tool_hint": "goal_trace"},
                {"description": "Determine root cause", "tool_hint": null}
            ],
            "success_criteria": ["Identified removal cause"]
        }"#;

        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.steps.len(), 3);
        assert_eq!(parsed.goal, "Find how Twitter task was removed");
        assert_eq!(parsed.success_criteria.len(), 1);
        assert!(parsed.contract.is_none(), "contract is optional");
    }

    #[test]
    fn test_parse_plan_response_with_contract_signals() {
        let json = r#"{
            "goal": "Update the deploy script",
            "steps": [
                {"description": "Read deploy.sh", "tool_hint": "read_file"},
                {"description": "Edit the retry flag", "tool_hint": "edit_file"}
            ],
            "success_criteria": ["deploy.sh contains the retry flag"],
            "contract": {
                "confidence": "high",
                "expects_mutation": true,
                "requires_observation": true,
                "task_kind": "change"
            }
        }"#;

        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        let contract = parsed.contract.unwrap();
        assert_eq!(contract.expects_mutation, Some(true));
        assert_eq!(contract.requires_observation, Some(true));
        assert_eq!(contract.task_kind.as_deref(), Some("change"));
        assert!(contract.mutation_scope.is_none());
        assert!(contract.forbidden_actions.is_empty());
    }

    #[test]
    fn test_parse_plan_response_with_partial_contract() {
        let json = r#"{
            "goal": "g",
            "steps": [{"description": "s", "tool_hint": null}],
            "contract": {"task_kind": "answer"}
        }"#;
        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        let contract = parsed.contract.unwrap();
        assert_eq!(contract.expects_mutation, None);
        assert_eq!(contract.task_kind.as_deref(), Some("answer"));
    }

    #[test]
    fn test_parse_semantic_task_shape_and_scoped_mutation() {
        let json = r#"{
            "goal": "Build and verify locally without publishing",
            "steps": [],
            "success_criteria": [],
            "contract": {
                "expects_mutation": true,
                "requires_observation": true,
                "task_kind": "change",
                "mutation_scope": "scoped",
                "forbidden_actions": ["deploy", "publish"],
                "constraint_evidence": ["without publishing"]
            },
            "task_shape": {
                "execution_mode": "inline",
                "confidence": "high",
                "independent_workstreams": 1,
                "requires_background_continuation": false
            }
        }"#;

        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        let contract = parsed.contract.unwrap();
        assert_eq!(contract.mutation_scope.as_deref(), Some("scoped"));
        assert_eq!(contract.forbidden_actions, ["deploy", "publish"]);
        assert!(planned_mutation_constraints_are_grounded(
            &contract,
            "Build and verify locally without publishing"
        ));
        assert!(!planned_mutation_constraints_are_grounded(
            &contract,
            "Build and verify the project"
        ));
        let shape = parsed.task_shape.unwrap();
        assert_eq!(shape.execution_mode.as_deref(), Some("inline"));
        assert_eq!(shape.confidence.as_deref(), Some("high"));
        assert_eq!(shape.independent_workstreams, Some(1));
    }

    #[test]
    fn scoped_evidence_cannot_ground_a_global_read_only_contract() {
        let signals = PlannedContractSignals {
            confidence: Some("high".to_string()),
            expects_mutation: Some(true),
            requires_observation: Some(true),
            required_effects: Some(vec!["local_source_write".to_string()]),
            task_kind: Some("change".to_string()),
            mutation_scope: Some("read_only".to_string()),
            forbidden_actions: vec!["deploy".to_string()],
            constraint_evidence: vec!["do not deploy".to_string()],
        };
        assert!(!planned_mutation_constraints_are_grounded(
            &signals,
            "Build the project locally, but do not deploy"
        ));
    }

    #[test]
    fn autonomous_assessment_mode_never_installs_steps() {
        assert!(!TaskAssessmentMode::AutonomousRouting.includes_step_plan());
        assert!(TaskAssessmentMode::GuidedPlan.includes_step_plan());
    }

    #[tokio::test]
    async fn autonomous_assessment_discards_model_generated_plan_scaffolding() {
        let response = crate::testing::MockProvider::text_response(
            r#"{
                "goal": "Update one file",
                "steps": [{"description": "Micromanaged step", "tool_hint": "edit_file"}],
                "success_criteria": ["Micromanaged criterion"],
                "contract": {
                    "task_kind": "change",
                    "expects_mutation": true,
                    "requires_observation": true,
                    "mutation_scope": "allowed",
                    "forbidden_actions": []
                },
                "task_shape": {
                    "execution_mode": "inline",
                    "confidence": "high",
                    "independent_workstreams": 1,
                    "requires_background_continuation": false
                }
            }"#,
        );
        let mut provider = crate::testing::MockProvider::with_responses(vec![response]);
        provider.skip_planning_calls = false;

        let assessment = generate_task_plan(
            Arc::new(provider),
            "gpt-5",
            "Update the file and verify it.",
            None,
            TaskAssessmentMode::AutonomousRouting,
            None,
        )
        .await
        .expect("assessment");

        assert!(assessment.steps.is_empty());
        assert!(assessment.success_criteria.is_empty());
        assert!(assessment.contract.is_some());
        assert_eq!(
            assessment
                .task_shape
                .as_ref()
                .and_then(|shape| shape.execution_mode.as_deref()),
            Some("inline")
        );
    }

    #[tokio::test]
    async fn guided_assessment_retains_concrete_plan() {
        let response = crate::testing::MockProvider::text_response(
            r#"{
                "goal": "Update one file",
                "steps": [
                    {"description": "Inspect the file", "tool_hint": "read_file"},
                    {"description": "Update the file", "tool_hint": "edit_file"}
                ],
                "success_criteria": ["The requested value is present"],
                "contract": {
                    "task_kind": "change",
                    "expects_mutation": true,
                    "requires_observation": true,
                    "mutation_scope": "allowed",
                    "forbidden_actions": []
                },
                "task_shape": {
                    "execution_mode": "inline",
                    "confidence": "high",
                    "independent_workstreams": 1,
                    "requires_background_continuation": false
                }
            }"#,
        );
        let mut provider = crate::testing::MockProvider::with_responses(vec![response]);
        provider.skip_planning_calls = false;

        let assessment = generate_task_plan(
            Arc::new(provider),
            "local-model",
            "Update the file.",
            None,
            TaskAssessmentMode::GuidedPlan,
            None,
        )
        .await
        .expect("assessment");

        assert_eq!(assessment.steps.len(), 2);
        assert_eq!(assessment.success_criteria.len(), 1);
    }

    #[test]
    fn test_parse_plan_truncates_at_7() {
        let steps: Vec<TaskPlanStep> = (0..10)
            .map(|i| TaskPlanStep {
                description: format!("Step {}", i),
                tool_hint: None,
            })
            .collect();
        let mut plan_steps = steps;
        plan_steps.truncate(MAX_PLAN_STEPS);
        assert_eq!(plan_steps.len(), 7);
    }
}
