use crate::router::Router;
use crate::traits::{ModelProvider, ProviderResponse};
use crate::utils::truncate_str;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::sync::Arc;
use std::time::Instant;
use tracing::{info, warn};

/// A planned step generated by the task-start planning call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct TaskPlanStep {
    pub description: String,
    #[serde(default)]
    pub tool_hint: Option<String>,
}

/// Completion-contract signals classified by the planning LLM. Unlike the
/// keyword-based contract inference (English-only), these come from the
/// model reading the actual request in any language. All fields optional —
/// absent fields leave the keyword-inferred contract untouched.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct PlannedContractSignals {
    #[serde(default)]
    pub expects_mutation: Option<bool>,
    #[serde(default)]
    pub requires_observation: Option<bool>,
    #[serde(default)]
    pub task_kind: Option<String>,
}

/// Raw response from the planning LLM call.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TaskPlanResponse {
    goal: String,
    steps: Vec<TaskPlanStep>,
    #[serde(default)]
    success_criteria: Vec<String>,
    #[serde(default)]
    contract: Option<PlannedContractSignals>,
}

/// Result of the task-start planning call.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub(crate) struct TaskPlan {
    pub goal: String,
    pub steps: Vec<TaskPlanStep>,
    pub success_criteria: Vec<String>,
    pub contract: Option<PlannedContractSignals>,
}

const MAX_PLAN_STEPS: usize = 7;

#[derive(Clone, Copy)]
pub(crate) struct PlannerTelemetryCtx<'a> {
    pub emitter: &'a crate::events::EventEmitter,
    pub state: &'a dyn crate::traits::TokenUsageStore,
    pub session_id: &'a str,
    pub task_id: &'a str,
}

async fn record_auxiliary_model_call(
    telemetry: Option<PlannerTelemetryCtx<'_>>,
    call_purpose: &str,
    model: &str,
    response: &ProviderResponse,
    latency_ms: u64,
) {
    let Some(telemetry) = telemetry else {
        return;
    };
    let (
        input_tokens,
        output_tokens,
        cached_input_tokens,
        cache_creation_input_tokens,
        fresh_input_tokens,
    ) = response
        .usage
        .as_ref()
        .map(|usage| {
            (
                usage.input_tokens,
                usage.output_tokens,
                usage.cached_input_tokens,
                usage.cache_creation_input_tokens,
                usage.fresh_input_tokens(),
            )
        })
        .unwrap_or((0, 0, None, None, None));
    crate::events::record_model_call_telemetry(
        telemetry.emitter,
        telemetry.state,
        crate::events::ModelCallTelemetryInput {
            session_id: telemetry.session_id.to_string(),
            task_id: telemetry.task_id.to_string(),
            call_purpose: Some(call_purpose.to_string()),
            iteration: Some(0),
            llm_call: crate::events::LlmCallData {
                call_id: None,
                call_purpose: Some(call_purpose.to_string()),
                task_id: telemetry.task_id.to_string(),
                iteration: Some(0),
                model: model.to_string(),
                final_model: Some(model.to_string()),
                fell_back: false,
                attempts: 1,
                latency_ms,
                prompt_ms: None,
                decode_ms: None,
                input_tokens,
                output_tokens,
                cached_input_tokens,
                cache_creation_input_tokens,
                fresh_input_tokens,
                est_input_tokens: None,
                tool_calls_count: response.tool_calls.len() as u32,
                offered_tools: Vec::new(),
                chosen_tools: Vec::new(),
                build_ms: None,
                prefix_hash_system: None,
                prefix_hash_pre_boundary: None,
                tool_defs_hash: None,
                session_summary_hash: None,
                tail_hash: None,
                prefix_hash_archived: None,
                boundary_pos: None,
                message_count: None,
                force_text: false,
                token_usage_present: response.usage.is_some(),
                failed: false,
                error: None,
            },
            token_usage: response.usage.clone(),
        },
    )
    .await;
}

/// Generate a task plan from the user's request.
///
/// Returns None if the planning call fails, times out, or returns
/// unparseable JSON. Failure is silent — the system operates as
/// it does today without a plan.
#[allow(dead_code)]
pub(crate) async fn generate_task_plan(
    provider: Arc<dyn ModelProvider>,
    model: &str,
    user_text: &str,
    conversation_context: Option<&str>,
    telemetry: Option<PlannerTelemetryCtx<'_>>,
) -> Option<TaskPlan> {
    let system = "You are a task planner. Analyze the user request and return a JSON plan. \
                  Return ONLY valid JSON, no markdown fences.";

    // Include conversation context from the sliding window so the planner
    // has the same narrative as the main LLM. Without this, short follow-ups
    // like "and for ibuprofen?" lose the original intent from earlier turns.
    let context_block = conversation_context
        .filter(|ctx| !ctx.is_empty())
        .map(|ctx| format!("Recent conversation context:\n{}\n\n", ctx))
        .unwrap_or_default();

    let user_prompt = format!(
        "{}Analyze this user request and create a step-by-step plan.\n\n\
         User request: \"{}\"\n\n\
         Return JSON only:\n\
         {{\n  \
           \"goal\": \"one-line summary of what the user wants\",\n  \
           \"steps\": [\n    \
             {{ \"description\": \"specific action step\", \"tool_hint\": \"likely tool name or null\" }}\n  \
           ],\n  \
           \"success_criteria\": [\n    \
             \"concrete criterion for task completion\"\n  \
           ],\n  \
           \"contract\": {{\n    \
             \"task_kind\": \"conversational|answer|check|find|change|deliver|schedule|monitor|diagnose\",\n    \
             \"expects_mutation\": true,\n    \
             \"requires_observation\": true\n  \
           }}\n\
         }}\n\n\
         Rules:\n\
         - 2-7 steps. Simple questions that need one lookup: 2 steps.\n\
         - Each step should be a concrete action, not vague \
           (\"search memory for twitter schedule\" not \"investigate\")\n\
         - tool_hint is advisory — helps understand step type\n\
         - success_criteria: what does \"done\" look like?\n\
         - contract.task_kind: what KIND of request this is (judge the user's \
           intent in whatever language they wrote it).\n\
         - contract.expects_mutation: true only if completing the request \
           requires creating/modifying files or external state. Generating \
           text INTO THE REPLY (a tweet, a poem, an explanation) is NOT a \
           mutation.\n\
         - contract.requires_observation: true if answering requires reading \
           live data first (files, command output, web, APIs) rather than \
           general knowledge.\n\
         - IMPORTANT: When the request contains MULTIPLE distinct actions \
           (create + run, write + execute + fix, build + deploy + verify), \
           each action MUST be its own step. Never collapse \"create X then run it\" \
           into a single step.\n\
         - When the task involves creating a file that processes other files, \
           ALWAYS start with an inspection step to understand the target files' format.\n\n\
         Examples of compound task decomposition:\n\
         \"Create a script and run it\" → 3 steps: inspect target files, create script, run script\n\
         \"Write tests then fix any failures\" → 3 steps: write tests, run tests, fix failures\n\
         \"Build a checker, run it, fix issues\" → 4 steps: inspect files, create checker, run checker, fix reported issues",
        context_block,
        truncate_str(user_text, 500)
    );

    let messages = vec![
        json!({ "role": "system", "content": system }),
        json!({ "role": "user", "content": user_prompt }),
    ];

    let call_start = Instant::now();
    let result = match tokio::time::timeout(
        std::time::Duration::from_secs(15),
        provider.chat(model, &messages, &[]),
    )
    .await
    {
        Ok(Ok(response)) => response,
        Ok(Err(e)) => {
            warn!(error = %e, "Task planning call failed");
            return None;
        }
        Err(_) => {
            warn!("Task planning call timed out (15s)");
            return None;
        }
    };
    record_auxiliary_model_call(
        telemetry,
        "task_planner",
        model,
        &result,
        call_start.elapsed().as_millis() as u64,
    )
    .await;

    let content = result.content.as_deref().unwrap_or("");

    let json_str = match crate::utils::extract_json_object(content) {
        Some(s) => s,
        None => {
            warn!("Task planning response: no valid JSON found");
            return None;
        }
    };

    let parsed: TaskPlanResponse = match serde_json::from_str(&json_str) {
        Ok(p) => p,
        Err(e) => {
            warn!(error = %e, "Task planning response unparseable");
            return None;
        }
    };

    if parsed.steps.is_empty() {
        return None;
    }

    let mut steps = parsed.steps;

    // For compound tasks (user asked to create+run, write+execute+fix, etc.),
    // ensure the plan has enough steps. If the LLM collapsed everything into
    // 1-2 steps, append execution/verification steps.
    if steps.len() < 3 && looks_like_compound_task(user_text) {
        let has_execution_step = steps.iter().any(|s| {
            let d = s.description.to_lowercase();
            ["run", "execute", "test"]
                .iter()
                .any(|word| crate::agent::contains_keyword_as_words(&d, word))
        });
        if !has_execution_step {
            steps.push(TaskPlanStep {
                description: "Run/execute the created artifact and capture output".to_string(),
                tool_hint: Some("terminal".to_string()),
            });
        }
        let has_fix_step = steps.iter().any(|s| {
            let d = s.description.to_lowercase();
            ["fix", "repair", "resolve"]
                .iter()
                .any(|word| crate::agent::contains_keyword_as_words(&d, word))
        });
        let lower = user_text.to_lowercase();
        if !has_fix_step
            && ["fix", "repair", "resolve"]
                .iter()
                .any(|word| crate::agent::contains_keyword_as_words(&lower, word))
        {
            steps.push(TaskPlanStep {
                description: "Fix any issues found in the previous step".to_string(),
                tool_hint: Some("edit_file".to_string()),
            });
        }
    }

    steps.truncate(MAX_PLAN_STEPS);

    info!(
        goal = %parsed.goal,
        step_count = steps.len(),
        "Task plan generated"
    );

    Some(TaskPlan {
        goal: parsed.goal,
        steps,
        success_criteria: parsed.success_criteria,
        contract: parsed.contract,
    })
}

/// Detect compound tasks that involve multiple distinct actions.
/// e.g., "create X then run it", "write a script and execute it, fix issues"
fn looks_like_compound_task(user_text: &str) -> bool {
    let lower = user_text.to_lowercase();

    // Use word-boundary matching to avoid false positives from filenames
    // like "checker.py" matching "check".
    let has_word = |kw: &str| crate::agent::contains_keyword_as_words(&lower, kw);

    // Count distinct action categories present
    let create_actions = ["create", "write", "build", "make", "generate"];
    let execute_actions = ["run", "execute", "test", "launch", "start"];
    let fix_actions = ["fix", "repair", "resolve", "correct", "patch"];
    // Multi-word phrases use .contains() since they're specific enough
    let verify_phrases = ["show me", "show me the"];

    let mut categories = 0u8;
    if create_actions.iter().any(|a| has_word(a)) {
        categories += 1;
    }
    if execute_actions.iter().any(|a| has_word(a)) {
        categories += 1;
    }
    if fix_actions.iter().any(|a| has_word(a)) {
        categories += 1;
    }
    if has_word("verify")
        || has_word("check")
        || has_word("display")
        || has_word("report")
        || verify_phrases.iter().any(|p| lower.contains(p))
    {
        categories += 1;
    }

    // Compound if 2+ distinct action categories
    categories >= 2
}

/// Determine whether the task-start planning call should be skipped.
///
/// Simple turns can still use tools in the normal loop; they do not need a
/// separate model call that restates the question as a two-step plan first.
#[cfg(test)]
fn should_skip_planning(
    _task_kind: &crate::agent::CompletionTaskKind,
    user_text: &str,
    is_acknowledgment: bool,
) -> bool {
    planning_skip_reason(user_text, is_acknowledgment).is_some()
}

pub(crate) fn planning_skip_reason(
    user_text: &str,
    is_acknowledgment: bool,
) -> Option<&'static str> {
    if is_acknowledgment {
        return Some("acknowledgment");
    }

    if crate::agent::is_internal_maintenance_intent(user_text) {
        return Some("orchestration_direct_return");
    }

    if matches!(
        crate::agent::classify_intent_complexity(user_text),
        crate::agent::IntentComplexity::Scheduled { .. }
    ) {
        return Some("orchestration_direct_return");
    }

    // Control commands — not tasks that need a plan.
    let lower = user_text.trim().to_lowercase();
    let control_commands = [
        "cancel",
        "stop",
        "nevermind",
        "never mind",
        "abort",
        "forget it",
        "forget that",
        "nvm",
    ];
    if control_commands.iter().any(|cmd| lower == *cmd) {
        return Some("control_command");
    }

    let planning_worthy_markers = [
        "analyze",
        "audit",
        "build",
        "change",
        "create",
        "debug",
        "deploy",
        "diagnose",
        "figure out",
        "fix",
        "implement",
        "inspect",
        "install",
        "investigate",
        "repair",
        "run",
        "send",
        "test",
        "update",
        "write",
    ];
    let planning_worthy = planning_worthy_markers
        .iter()
        .any(|marker| crate::agent::contains_keyword_as_words(&lower, marker));

    if !planning_worthy
        && !looks_like_compound_task(user_text)
        && matches!(
            crate::agent::classify_intent_complexity(user_text),
            crate::agent::IntentComplexity::Simple
        )
    {
        return Some("simple_turn");
    }

    None
}

/// Re-planner: evaluates whether the current plan step is complete.
///
/// Called after each tool execution round when the current step has had
/// enough tool calls since the last evaluation. Uses a focused LLM
/// prompt to judge step completion.
///
/// Returns Some(evidence) if the step is complete, None if not or on failure.
pub(crate) async fn evaluate_step_completion(
    provider: Arc<dyn ModelProvider>,
    router: &Router,
    step_description: &str,
    tool_results_summary: &str,
    telemetry: Option<PlannerTelemetryCtx<'_>>,
) -> Option<String> {
    let model = router.select(crate::router::Tier::Primary).to_string();

    let prompt = format!(
        "You are evaluating whether a task step is complete.\n\n\
         Current step: \"{}\"\n\n\
         Tool results from this step:\n{}\n\n\
         Has the agent gathered enough information or completed enough work \
         to move to the next step? Be practical \u{2014} if the key information \
         has been found, the step is complete even if more could theoretically \
         be explored.\n\n\
         Return JSON only:\n\
         {{\"complete\": true/false, \"evidence\": \"brief summary of what was accomplished\"}}",
        step_description,
        truncate_str(tool_results_summary, 1500)
    );

    let messages = vec![
        json!({
            "role": "system",
            "content": "You are a task progress evaluator. Return ONLY valid JSON."
        }),
        json!({ "role": "user", "content": prompt }),
    ];

    let call_start = Instant::now();
    let result = match tokio::time::timeout(
        std::time::Duration::from_secs(10),
        provider.chat(&model, &messages, &[]),
    )
    .await
    {
        Ok(Ok(response)) => response,
        Ok(Err(e)) => {
            warn!(error = %e, "Re-planner call failed");
            return None;
        }
        Err(_) => {
            warn!("Re-planner call timed out (10s)");
            return None;
        }
    };
    record_auxiliary_model_call(
        telemetry,
        "replanner",
        &model,
        &result,
        call_start.elapsed().as_millis() as u64,
    )
    .await;

    let content = result.content.as_deref().unwrap_or("");
    let json_str = crate::utils::extract_json_object(content)?;

    #[derive(Deserialize)]
    struct ReplanResult {
        complete: bool,
        #[serde(default)]
        evidence: String,
    }

    match serde_json::from_str::<ReplanResult>(&json_str) {
        Ok(r) if r.complete => {
            info!(evidence = %r.evidence, "Re-planner: step complete");
            Some(r.evidence)
        }
        Ok(_) => {
            info!("Re-planner: step not yet complete");
            None
        }
        Err(e) => {
            warn!(error = %e, "Re-planner response parse failed");
            None
        }
    }
}

/// Build a summary of recent tool calls for the re-planner prompt.
pub(crate) fn summarize_tool_calls_for_replan(tool_calls: &[String], max_entries: usize) -> String {
    tool_calls
        .iter()
        .rev()
        .take(max_entries)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .map(|call| {
            let display = crate::agent::post_task::display_tool_call(call);
            format!("- {}", display)
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_skips_simple_conversational_turn() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "hello there how are you doing today",
            false
        ));
    }

    #[test]
    fn test_should_skip_simple_short_text() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(&CompletionTaskKind::Find, "hi", false));
    }

    #[test]
    fn test_should_skip_direct_recall_question() {
        use crate::agent::CompletionTaskKind;
        assert_eq!(
            planning_skip_reason("What's my dad's name?", false),
            Some("simple_turn")
        );
        assert!(should_skip_planning(
            &CompletionTaskKind::Answer,
            "What's the source of that?",
            false
        ));
    }

    #[test]
    fn test_should_skip_control_commands() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "cancel",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "stop",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "nevermind",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "nvm",
            false
        ));
        assert!(should_skip_planning(
            &CompletionTaskKind::Conversational,
            "abort",
            false
        ));
    }

    #[test]
    fn test_should_skip_internal_maintenance() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Change,
            "Analyze the knowledge base and identify stale entries, then process embeddings, consolidate memories, find outdated data, and report on decay old facts",
            false
        ));
    }

    #[test]
    fn test_should_skip_scheduled_direct_return() {
        use crate::agent::CompletionTaskKind;
        assert_eq!(
            planning_skip_reason("Check deployment tomorrow at 9am", false),
            Some("orchestration_direct_return")
        );
        assert!(should_skip_planning(
            &CompletionTaskKind::Change,
            "Check deployment tomorrow at 9am",
            false
        ));
    }

    #[test]
    fn test_should_skip_acknowledgment() {
        use crate::agent::CompletionTaskKind;
        assert!(should_skip_planning(
            &CompletionTaskKind::Change,
            "ok thanks that looks good",
            true
        ));
    }

    #[test]
    fn test_should_not_skip_investigative_question() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Find,
            "Can you figure out how the Twitter scheduled task got removed?",
            false
        ));
    }

    #[test]
    fn test_should_not_skip_change_task() {
        use crate::agent::CompletionTaskKind;
        assert!(!should_skip_planning(
            &CompletionTaskKind::Change,
            "Create a website about zeigarnik effect and deploy to cloudflare",
            false
        ));
    }

    #[test]
    fn test_parse_plan_response() {
        let json = r#"{
            "goal": "Find how Twitter task was removed",
            "steps": [
                {"description": "Search memory for twitter schedule", "tool_hint": "manage_memories"},
                {"description": "Check goal trace", "tool_hint": "goal_trace"},
                {"description": "Determine root cause", "tool_hint": null}
            ],
            "success_criteria": ["Identified removal cause"]
        }"#;

        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.steps.len(), 3);
        assert_eq!(parsed.goal, "Find how Twitter task was removed");
        assert_eq!(parsed.success_criteria.len(), 1);
        assert!(parsed.contract.is_none(), "contract is optional");
    }

    #[test]
    fn test_parse_plan_response_with_contract_signals() {
        let json = r#"{
            "goal": "Update the deploy script",
            "steps": [
                {"description": "Read deploy.sh", "tool_hint": "read_file"},
                {"description": "Edit the retry flag", "tool_hint": "edit_file"}
            ],
            "success_criteria": ["deploy.sh contains the retry flag"],
            "contract": {
                "expects_mutation": true,
                "requires_observation": true,
                "task_kind": "change"
            }
        }"#;

        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        let contract = parsed.contract.unwrap();
        assert_eq!(contract.expects_mutation, Some(true));
        assert_eq!(contract.requires_observation, Some(true));
        assert_eq!(contract.task_kind.as_deref(), Some("change"));
    }

    #[test]
    fn test_parse_plan_response_with_partial_contract() {
        let json = r#"{
            "goal": "g",
            "steps": [{"description": "s", "tool_hint": null}],
            "contract": {"task_kind": "answer"}
        }"#;
        let parsed: TaskPlanResponse = serde_json::from_str(json).unwrap();
        let contract = parsed.contract.unwrap();
        assert_eq!(contract.expects_mutation, None);
        assert_eq!(contract.task_kind.as_deref(), Some("answer"));
    }

    #[test]
    fn test_parse_plan_truncates_at_7() {
        let steps: Vec<TaskPlanStep> = (0..10)
            .map(|i| TaskPlanStep {
                description: format!("Step {}", i),
                tool_hint: None,
            })
            .collect();
        let mut plan_steps = steps;
        plan_steps.truncate(MAX_PLAN_STEPS);
        assert_eq!(plan_steps.len(), 7);
    }

    #[test]
    fn test_compound_task_create_and_run() {
        assert!(looks_like_compound_task(
            "Create a Python script and run it to check all blog posts"
        ));
    }

    #[test]
    fn test_compound_task_create_run_fix() {
        assert!(looks_like_compound_task(
            "Write a checker script, execute it, and fix any issues found"
        ));
    }

    #[test]
    fn test_compound_task_build_and_verify() {
        assert!(looks_like_compound_task(
            "Build the project and show me the test results"
        ));
    }

    #[test]
    fn test_not_compound_simple_create() {
        assert!(!looks_like_compound_task(
            "Create a Python script at ~/projects/blog/tools/checker.py"
        ));
    }

    #[test]
    fn test_not_compound_simple_question() {
        assert!(!looks_like_compound_task("What time is it in Tokyo?"));
    }

    #[test]
    fn test_compound_task_generate_and_test() {
        assert!(looks_like_compound_task(
            "Generate unit tests for the router module, then run them"
        ));
    }
}
